# Generated by Django 2.2.3 on 2019-08-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_connection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='creator',
            new_name='follower',
        ),
    ]
